# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hardware_ai.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'hardware_ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11hardware_ai.proto\x12\x0bhardware_ai\"P\n\x10RecognizeRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x11\n\ttenant_id\x18\x02 \x01(\t\x12\x15\n\roriginal_name\x18\x03 \x01(\t\"=\n\x0b\x42oundingBox\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\"h\n\x0c\x44\x65tectedItem\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12%\n\x03\x62ox\x18\x02 \x01(\x0b\x32\x18.hardware_ai.BoundingBox\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\"r\n\x11RecognizeResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x13\n\x0btotal_items\x18\x03 \x01(\x05\x12(\n\x05items\x18\x04 \x03(\x0b\x32\x19.hardware_ai.DetectedItem\"e\n\rEnrollRequest\x12\x12\n\nimage_path\x18\x01 \x01(\t\x12\x0b\n\x03sku\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x12\n\nproduct_id\x18\x04 \x01(\t\x12\x11\n\ttenant_id\x18\x05 \x01(\t\"1\n\x0e\x45nrollResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xac\x01\n\nHardwareAI\x12P\n\rRecognizeJobs\x12\x1d.hardware_ai.RecognizeRequest\x1a\x1e.hardware_ai.RecognizeResponse\"\x00\x12L\n\x0f\x45nrollEmbedding\x12\x1a.hardware_ai.EnrollRequest\x1a\x1b.hardware_ai.EnrollResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hardware_ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOGNIZEREQUEST']._serialized_start=34
  _globals['_RECOGNIZEREQUEST']._serialized_end=114
  _globals['_BOUNDINGBOX']._serialized_start=116
  _globals['_BOUNDINGBOX']._serialized_end=177
  _globals['_DETECTEDITEM']._serialized_start=179
  _globals['_DETECTEDITEM']._serialized_end=283
  _globals['_RECOGNIZERESPONSE']._serialized_start=285
  _globals['_RECOGNIZERESPONSE']._serialized_end=399
  _globals['_ENROLLREQUEST']._serialized_start=401
  _globals['_ENROLLREQUEST']._serialized_end=502
  _globals['_ENROLLRESPONSE']._serialized_start=504
  _globals['_ENROLLRESPONSE']._serialized_end=553
  _globals['_HARDWAREAI']._serialized_start=556
  _globals['_HARDWAREAI']._serialized_end=728
# @@protoc_insertion_point(module_scope)
